version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: .Dockerfile  # 显式指定为 .Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./backend
      dockerfile: .Dockerfile  # 显式指定为 .Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

